### ISSUE TITLE
Calling js method onSaveInstanceState failed TypeError: Cannot read property '_domId' of undefined

### ISSUE THREAD

**Issue by jessorlisa** [NativeScript/angular#25]
**Environment**
 - CLI: `├── nativescript@8.0.2`
 - Cross-platform modules: `├── @nativescript/core@8.0.8`
 - Android Runtime: `├── @nativescript/android@8.0.0`
 - iOS Runtime: `├── @nativescript/ios@6.5.4 (JSC)`
 - Plugin(s):
 - NativeScript-Angular: `├── @nativescript/angular@12.0.6`
 - Angular:`├── @angular/core@12.2.0`
 
**Describe the bug**
Since upgrading to Angular 12 the following report can be found multiple times in Crashlytics:

```
Fatal Exception: com.tns.NativeScriptException: Calling js method onSaveInstanceState failed
TypeError: Cannot read property '_domId' of undefined
       at com.tns.Runtime.callJSMethodNative(Runtime.java)
       at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
       at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
       at com.tns.Runtime.callJSMethod(Runtime.java:1175)
       at com.tns.Runtime.callJSMethod(Runtime.java:1153)
       at com.tns.Runtime.callJSMethod(Runtime.java:1149)
       at com.tns.NativeScriptActivity.onSaveInstanceState(NativeScriptActivity.java:55)
       at android.app.Activity.performSaveInstanceState(Activity.java:2075)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1486)
       at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5694)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5001)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4960)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5040)
       at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```
It seems the error already was reported before [here](https://github.com/NativeScript/angular/issues/8), the issue was closed but the "possible fix" is not yet released: https://github.com/NativeScript/NativeScript/pull/9447

**To Reproduce**
As of today, this does not happen in development? 🤷🏻‍♀️ 

**Expected behavior**
No crash reports

**Comment by edusperoni** [comment]
Closing this as it will be fixed as part of NativeScript 8.1 (https://github.com/NativeScript/NativeScript/pull/9447)
