### ISSUE TITLE
Bug: Named Outlet non responsive after `clearHistory` navigation

### ISSUE THREAD

**Issue by wSedlacek** [NativeScript/angular#39]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.1.3
 - Cross-platform modules: NA
 - Android Runtime: 8.1.1
 - iOS Runtime: Not Tested
 - Plugin(s): @nativescript-community/ui-material-bottomnavigationbar
 - NativeScript-Angular: 12.2.0
 - Angular: 12.2.0
 
**Describe the bug**
When navigating to a nested route (one with a named outlet) after a `clearHistory` a navigation event would fire, but the outlet would not be updated

**To Reproduce**
Clone https://github.com/herefishyfish/named-router-navigation-bug
Start Android application
Press "Go to dashboard"
Press "Nested route in navbar"
Press Notifications tab 
Press Todos tab
Press "Nested route in navbar"

**Expected behavior**
For the second press of `Nested route in navbar` to navigate to the nested route.

**Sample project**
https://github.com/herefishyfish/named-router-navigation-bug

**Additional context**
There was a few messages in Discord about this:
https://discord.com/channels/603595811204366337/606457628729671691/895530953068408894

**Comment by timdoege** [comment]
Just a side note: Running with HMR on Android, I get this crash when doing code changes using PR 38
```
JS: TypeError: Cannot read property 'outlet' of null TypeError: Cannot read property 'outlet' of null
JS:     at PageRouterOutlet.ngOnDestroy (file: node_modules/@nativescript/angular/fesm2015/nativescript-angular.js:5836:0)
JS:     at executeOnDestroys (file: node_modules/@angular/core/fesm2015/core.js:7418:0)
JS:     at cleanUpView (file: node_modules/@angular/core/fesm2015/core.js:7321:0)
JS:     at destroyViewTree (file: node_modules/@angular/core/fesm2015/core.js:7147:0)
JS:     at destroyLView (file: node_modules/@angular/core/fesm2015/core.js:7299:0)
JS:     at RootViewRef.destroy (file: node_modules/@angular/core/fesm2015/core.js:22663:0)
JS:     at ComponentRef$1.destroy (file: node_modules/@angular/core/fesm2015/core.js:25197:0)
JS:     at file: node_modules/@nativescript/angular/fesm2015/nativescript-angular.js:1783:0
JS:     at file: node_modules/@nativescript/angular/fesm2015/nativescript-angular.js:1756:0
```

which is this line from the PR:

```
   5836         if (this.parentContexts.getContext(this.name).outlet === this) {
   5837             // Clear accumulated modal view page cache when page-router-outlet
   5838             // destroyed on modal view closing
   5840             this.parentContexts.onChildOutletDestroyed(this.name);
   5841         }
```

**Comment by wSedlacek** [comment]
@timdoege I have updated my PR to account for the response being `null`
Perhaps in a future update strict TypeScript mode can be enabled on this repo.

**Comment by timdoege** [comment]
@wSedlacek Great - I will give your update a spin this week, thanks.

Regarding repo the https://github.com/NativeScript/login-tab-navigation-ng
you should be able to run my PR 

https://github.com/NativeScript/login-tab-navigation-ng/pull/21

which moves it to NS 8.1 / Angular 12 (and MD bottom navigation).

**Comment by wSedlacek** [comment]
Thank you. I will give https://github.com/NativeScript/login-tab-navigation-ng/pull/21 a shot.
