### ISSUE TITLE
Cannot read property '_domId' of undefined after upgrading to Angular 12

### ISSUE THREAD

**Issue by Hugo-Dlg** [NativeScript/angular#8]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.0.2 version and is up to date.
✔ Component @nativescript/core has 8.0.8 version and is up to date.
✔ Component @nativescript/ios has 8.0.0 version and is up to date.
✔ Component @nativescript/android has 8.0.0 version and is up to date.

**Describe the bug**
I followed the guide to upgrade to Nativescript Angular 12 (https://blog.nativescript.org/nativescript-angular-12/index.html) and when I run a tns run android I'm getting this error :
```System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onSaveInstanceState failed
System.err: TypeError: Cannot read property '_domId' of undefined
System.err:
System.err: StackTrace:
System.err: onSaveInstanceState(file: src\webpack:\greenperformer\node_modules\@nativescript\core\ui\frame\index.android.js:965:0)
System.err:     at onSaveInstanceState(file: src\webpack:\greenperformer\node_modules\@nativescript\core\ui\frame\activity.android.js:27:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.NativeScriptActivity.onSaveInstanceState(NativeScriptActivity.java:55)
System.err:     at android.app.Activity.performSaveInstanceState(Activity.java:2169)
System.err:     at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1625)
System.err:     at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5680)
System.err:     at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5051)
System.err:     at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5016)
System.err:     at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5090)
System.err:     at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:233)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:8010)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**To Reproduce**
Update my Ns 8, Angular 11 project to Angular 12

**Expected behavior**
That it builds and works well

**Comment by edusperoni** [comment]
Hey @Hugo-Dlg.

Can you share your `main.ts` and `app.component.html`?

**Comment by Hugo-Dlg** [comment]
Hello,

main.ts : 
```ts
import { platformNativeScript, runNativeScriptAngularApp } from '@nativescript/angular';

import { AppModule } from './app/app.module';

runNativeScriptAngularApp({
	appModuleBootstrap: () => platformNativeScript().bootstrapModule(AppModule)
});
```

app.component.html :
```html
<RadSideDrawer transition="SlideInOnTopTransition" [gesturesEnabled]="sideDrawerEnabled">
    <GridLayout tkDrawerContent style="background-color: #007e65;">
        <Scrollview style="background-color: #007e65;">
            <GridLayout height="100%" rows="auto, auto, auto, auto, auto, auto, auto, auto, auto, auto, auto"
                class="layout_header">
                <GridLayout row="0" columns='60, *' class="m-y-8" style="margin-bottom: 20;">
                    <Label col="0" text="&#xf00d;" class="fas_header" (tap)="closeDrawer()"></Label>
                    <Label col="1" text="Menu" class="label_header"></Label>
                </GridLayout>
                <GridLayout row="{{idx + 1}}" class="m-y-8" columns="60, *" *ngFor="let item of routes; let idx = index"
                    (tap)="closeDrawer()">
                    <Label col="0" [text]="item.icon" class="fas"></Label>
                    <Label col="1" textWrap="true" [text]="item.label" [nsRouterLink]="[item.link]"
                        [nsRouterLinkActive]="['selected']" [nsRouterLinkActiveOptions]="{exact: true}"></Label>
                </GridLayout>
                <StackLayout row="8" class="hr" style="width: 90%; border-color: black; opacity: 0.3;">
                </StackLayout>
                <GridLayout row="9" columns='60, *' class="m-y-8" (tap)="closeDrawer()">
                    <Label col="0" text="&#xf05a;" class="fas"></Label>
                    <Label col="1" textWrap="true" text="{{ ('App.Drawer.About') | L }}"
                        [nsRouterLink]="['/final/about']" [nsRouterLinkActive]="['selected']"
                        [nsRouterLinkActiveOptions]="{exact: true}"></Label>
                </GridLayout>
                <GridLayout row="10" columns='60, *'>
                    <Label col="0" text="&#xf2f5;" class="m-y-8" class="fas"></Label>
                    <Label col="1" (tap)="logOut()" text="{{ ('App.Drawer.LogOut') | L }}"></Label>
                </GridLayout>
            </GridLayout>
        </Scrollview>
    </GridLayout>
    <page-router-outlet tkMainContent ></page-router-outlet>
</RadSideDrawer>
```

In the app.component.html, I defined my drawer that I use in my app.
For the angular update steps, I upgraded my packages to 12.0.4 (also tried with 12.0.0), I created the polyfills file and paste the content as written in the tutorial and also I included the polyfills file in the tsconfig.json

Feel free to ask for anything else !

**Comment by edusperoni** [comment]
Can you show your `AppModule` as well?

I have a fix for this issue, but I'm curious as to why I'm not able to reproduce it.

Theoretically `onSaveInstanceState` should never be called so early in the app lifecycle (in your case it's being called before the rootView is being set, which happens before the first frame of the app). Are you using an async APP_INITIALIZER by any chance?

**Comment by Hugo-Dlg** [comment]
Here it is : 
```ts
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "@nativescript/angular";
import { NativeScriptUISideDrawerModule } from "nativescript-ui-sidedrawer/angular";
import { registerElement } from '@nativescript/angular';
registerElement('LineChart', () => require('@nativescript-community/ui-chart/charts').LineChart);
registerElement('BarChart', () => require('@nativescript-community/ui-chart/charts').BarChart);
import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

// requettes http
import { NativeScriptHttpClientModule } from "@nativescript/angular";
import { HttpClientModule } from "@angular/common/http";
// réactive form
import { NativeScriptFormsModule } from "@nativescript/angular";
import { ReactiveFormsModule } from "@angular/forms";

import { HomeComponent } from "./home/home.component";
import { FinalModule } from "./features/Final/final.module";
// multilingue
import { NativeScriptLocalizeModule } from "@nativescript/localize/angular";
import { NativeScriptMaterialBottomNavigationModule } from "@nativescript-community/ui-material-bottom-navigation/angular";
// bottomsheet
import { NativeScriptMaterialBottomSheetModule } from "@nativescript-community/ui-material-bottomsheet/angular";


@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        AppRoutingModule,
        NativeScriptMaterialBottomNavigationModule,
        NativeScriptModule,
        NativeScriptUISideDrawerModule,
        NativeScriptHttpClientModule,
        HttpClientModule,
        NativeScriptLocalizeModule,
        NativeScriptFormsModule,
        ReactiveFormsModule,
        FinalModule,
        NativeScriptMaterialBottomSheetModule.forRoot(),
    ],
    declarations: [
        AppComponent,
        HomeComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AppModule {
}
```
I don't know if it can helps but my project is build with 3 Modules, the app one for the login screen and a final/garage one depending of account type, same for routing

**Comment by Hugo-Dlg** [comment]
Alright so I came with some news, I tried with multiple settings and I managed to see that it works very well with Emulator, I had  a Pixel 3a emulated with Android Studio and I could launch my app without any problem while on my own Phone (One plus 8Pro) I got this error.

And also, I'm getting a new Error, in my header I call an other component where people can pick vehicule, like this : 
```html
<ActionBar>
	<NavigationButton visibility="collapsed"></NavigationButton>
	<GridLayout columns="50, *, 50">
	  <Image col="0" src="res://menu" width="20" height="20" (tap)="onDrawerTap()">
	  </Image>
	  <Label col="1" class="action-label" [text]="'App.Drawer.Refuel' | L"></Label>
	  <ns-picker col="2"></ns-picker>
	</GridLayout>
  </ActionBar>
  ```
  It was working on Nativescript Angular 11 but now I got a new error : 
  ```
 JS: ERROR UnsubscriptionError: 1 errors occurred during unsubscription:
JS: 1) TypeError: Right-hand side of 'instanceof' is not an object
JS: ERROR TypeError: Right-hand side of 'instanceof' is not an object
```

**Comment by edusperoni** [comment]
@Hugo-Dlg that's really odd. This error appears when we do `instanceof null` for example. That error might be something that angular 12 introduced (they seem to be showing more template errors, instead of just ignoring).

If you can find the subscription that's giving you issues we can work out what's going on. In some occasions it's a polyfill that's missing for the NativeScript platform that is present in the Web platform.

https://github.com/NativeScript/NativeScript/pull/9447 should fix your first issue, though, so expect a release soon™.

**Comment by Hugo-Dlg** [comment]
I got some observer with subscribe, but I used to do take(1) to do it only once and preventing my observer to keep listening and waiting.

But I found my issue, it's related to "@nativescript-community/ui-material-bottomsheet/angular"; When I try to open one, I got this error about instanceOf, for the unsubscribtion error, I don't know I'll try to find, maybe because with the picker I got a subscribe that unsubscribe when I leave the page :
```ts
    const obs = this.vehicleService.watchStorage().subscribe(
      () => {
        this.idVehicle = getString('idVehicle');
        this.modelVehicle = getString('modelVehicle');
      },
    )

    this.page.on('navigatingFrom', () => {
      // run destroy code
      obs.unsubscribe();
    })
```
Thanks again for your help, I'll write an issue with bottom sheet repository developers. If you find anything about the unsubscription, I'm listening ! 😄

**Comment by edusperoni** [comment]
what's the `watchStorage` code like?

You might be running some unsubscribe code there that's showing the error.

**Comment by Hugo-Dlg** [comment]
```ts
  watchStorage(): Observable<string> {
    return this.storageSub.asObservable();
  }

  setStorage(idVehicle: string, modelVehicle) {
    this.setLocalStorage('idVehicle', idVehicle);
    this.setLocalStorage('modelVehicle', modelVehicle);
    this.storageSub.next(idVehicle);
  }

  deleteStorage() {
    this.deleteLocalStorage('idVehicle');
    this.deleteLocalStorage('modelVehicle');
    this.storageSub.next();
  }

  private setLocalStorage(key: string, value: string) {
    try {
      this.deleteLocalStorage(key)
    }
    catch (error) { }
    setString(key, value);
  }

  private deleteLocalStorage(key: string) {
    remove(key);
  }
```

And my storageSub is a   ```private storageSub = new Subject<string>();```

They got a new value where next can't be empty, maybe this cause the unsubscription error

**Comment by edusperoni** [comment]
@Hugo-Dlg Really really odd, as there's nothing on the picker that indicates this. You can try updating your `zone.js` and see if that solves it

**Comment by Hugo-Dlg** [comment]
Hmm I have an idea, maybe because of the new main.ts, for bottomsheet, I have to do an install in the main.ts but it look like it's not working because I got a Ts 2307, cannot find module bottomSheet. 
Here's the main.ts with the bottomsheet install :
```ts
import { platformNativeScript, runNativeScriptAngularApp } from '@nativescript/angular';

import { AppModule } from './app/app.module';
import { install } from "@nativescript-community/ui-material-bottomsheet";

install();
runNativeScriptAngularApp({
	appModuleBootstrap: () => platformNativeScript().bootstrapModule(AppModule)
});
```
I tried to put it in the runNativeScriptAngularApp but haven't find a way yet

**Comment by edusperoni** [comment]
Hm, we might have forgotten to export that class then, I'll take a look

**Comment by Hugo-Dlg** [comment]
Anyway thanks for all your answers and help, have a great day !
